### ISSUE TITLE
user with edit rights can add new users with admin rights

### ISSUE THREAD

**Issue by triinjassov** [Teamweek/teamweek#1003]
f you give a member edit rights with no access to billing they can then create new members and/or give rights to others including billing access.

**Comment by herkyl** [comment]
This needs discussion on wether edit right users should be able to add users in the first place

**Comment by herkyl** [comment]
Only admins should be able to alter teams

**Comment by herkyl** [comment]
Closing this issue as this is part of a bigger issue we have now: https://github.com/Teamweek/teamweek/issues/1009
