### ISSUE TITLE
updates inside TW only show up for other users after refresh

### ISSUE THREAD

**Issue by triinjassov** [Teamweek/teamweek#1005]
We have been using teamweek for the past month and we are not deciding if
we want to move forward in getting one of your plans. The application
proved user friendly so far and with good features.

But one thing lacking would be the sync:

- EX: If I change something in teamweek, add a project, task, or
re-order items around. How is this synced to the other users using
teamweek. Because so far they do not seem to see these changes in real-time
and they need to refresh.
- EX2: I had a problem recently where because I did not refresh the page
I have created tasks for the whole week but they have been previously
created by another person. And I did not see them.

User will specify whether they only use web or mobile, iPad as well.

Case: 189300

**Comment by herkyl** [comment]
Seems to be working
