### ISSUE TITLE
Password max length 20 characters is not enough

### ISSUE THREAD

**Issue by webervin** [Teamweek/teamweek#146]
password managers have bigger defaults

**Comment by arcz** [comment]
Is 100 characters max ok?

**Comment by webervin** [comment]
I think it would be ok.
currently password managers generate token of 25....50 chars.

are you using some kind of hashing function that produces hash same length
as password?

**Comment by herkyl** [comment]
If we told you we had to kill you @webervin MUHAHAHA :hocho:
