### ISSUE TITLE
Admins' badge on timeline (frontend)

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#448]
Only admins should see who is admin user. In other words, only admins can see admin badges- stars
![admin_icon](https://cloud.githubusercontent.com/assets/5929570/4732953/b94a5748-59c2-11e4-9d49-e67d1bad3774.png)

There are 4 different levels: 
1. admin - can edit everything and see billing page
2. full user - can edit everything, but cannot see billing page
3. viewer/ read-only user with email - cannot see billing page, cannot see import page, cannot edit anything, cannot see "add people" button, cannot open users' popups, cannot drag users, cannot see "backlog" button, cannot add/ edit groups (hide plus and edit icons in groups' popup), cannot add milestones. can navigate, can use zoom levels, can see groups, can share and print. it's a bit similar to shared view. 
4. dummy user without email - cannot sign in

NB! admins can name/ designate admin users and decide whether others are full users or read-only users.

**Comment by miscer** [comment]
What is the difference between a blue and a yellow star?

**Comment by maritmartin** [comment]
it's just the users' background color, what you can see when they have no profile picture.
