### ISSUE TITLE
Overview of different access levels (frontend, backend)

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#449]
There are 4 different levels: 
1. admin - can edit everything and see billing page
2. full user - can edit everything, but cannot see billing page. 
3. viewer/ read-only user with email - cannot see billing page, cannot see import page, cannot edit anything, cannot see "add people" button, cannot open users' popups, cannot drag users, cannot see "backlog" button, cannot add/ edit groups (hide plus and edit icons in groups' popup), cannot add milestones. can navigate, can use zoom levels, can see groups, can share? and print?. it's a bit similar to shared view. 
4. dummy user without email - cannot sign in

NB! admins can name/ designate admin users and decide whether others are full users or read-only users.

Admin badges:
![admin_icon](https://cloud.githubusercontent.com/assets/5929570/4733557/ddc7985e-59c9-11e4-9ec5-a4cbaf51339b.png)

Marking a user as an admin:
![user_settings1](https://cloud.githubusercontent.com/assets/5929570/4733567/fbc08352-59c9-11e4-9370-c7d438d0e74f.png)

Deciding whether others are full users or read-only users:
![settings_users_access](https://cloud.githubusercontent.com/assets/5929570/4733587/33c44ed2-59ca-11e4-98c1-f13779dc5a2d.png)

Giving more information about that decision:
![default](https://cloud.githubusercontent.com/assets/5929570/4733600/5f0703be-59ca-11e4-83e6-ec69fb8212a4.png)

**Comment by arcz** [comment]
Can full user change other users role (bacuse he can edit everything)?

**Comment by maritmartin** [comment]
yes.

**Comment by marektihkan** [comment]
Can full user also change others to Admins?
