### ISSUE TITLE
Admins can decide whether others are full users or read-only users (frontend)

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#451]
Only admins can do that, others cannot see that option.

![settings_users_access](https://cloud.githubusercontent.com/assets/5929570/4733666/2fda9514-59cb-11e4-8952-128d96c83e23.png)

![default](https://cloud.githubusercontent.com/assets/5929570/4733668/32c0e04e-59cb-11e4-9d7e-56d06bed3f8b.png)

![screen shot 2014-10-22 at 14 43 25](https://cloud.githubusercontent.com/assets/5929570/4735441/a5fde63c-59e0-11e4-8556-3e1225984e49.png)

**Comment by arcz** [comment]
This option is rather accout preference than user, please correct me if I am wrong. Switching for example "hide weekends" switches them on all our accounts, but I suppose "users can edit tasks" works only for current account thus it is not concerning specific user but rather account.

**Comment by maritmartin** [comment]
yes, account preference that only admins can see. maybe in the future we have to separate those parts ( user preference and account preference), but not at the moment.
