### ISSUE TITLE
Ical feed popup

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#490]
![screenshot 2014-10-30 16 30 26](https://cloud.githubusercontent.com/assets/5929570/4845027/4d83cd20-6041-11e4-9400-bc13a79eaad7.png)
![screenshot 2014-10-30 16 29 44](https://cloud.githubusercontent.com/assets/5929570/4845028/4eee7d54-6041-11e4-9b28-d56c593c7436.png)

**Comment by arcz** [comment]
@miscer @herkyl backend is finished, could you make this popup? I only added button to share menu on frontend side

**API routes:**
*Managing token:*
POST      /api/v3/:account_id/sharing/icalendar # creates and if created refeshes token
DELETE  /api/v3/:account_id/sharing/icalendar # removes token

*Getting feed:*
GET         /api/v3/sharing/icalendar/:share_token # returns 'text/calendar' iCal feed
