### ISSUE TITLE
Add color selection for milestones

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#582]

**Comment by miscer** [comment]
What should the color button in the milestone popup look like if no color is set?

![screen shot 2015-01-26 at 18 04 33](https://cloud.githubusercontent.com/assets/1036313/5905148/de503bac-a585-11e4-9cc7-075caad0f681.png)

**Comment by herkyl** [comment]
I think we need a default color?

**Comment by maritmartin** [comment]
alari: btw, while dragging a milestone, it reverts back to the original green colour

**Comment by marektihkan** [comment]
Milestone have same default color as task (code: 21)
