### ISSUE TITLE
Sign-up request when clicking on some of the features in Demo

### ISSUE THREAD

**Issue by starfild** [Teamweek/teamweek#620]
If user wants to:
1) Create new group
2) Create new user
3) Share/Print 
4) Add something to backlog

then inline sign-up window/box appears with the text:

"Unleash the full version of Teamweek. Sign-up for free to try all the features"
and then the usual lines : address, name 
![screen shot 2015-01-13 at 11 09 09](https://cloud.githubusercontent.com/assets/9819262/5720562/8127f64c-9b2e-11e4-8553-e5b9e81aeeed.png)

**Comment by herkyl** [comment]
zoomhttps://drive.google.com/file/d/0B2Zd5TrGbCKgYlhscWFMMEwwVFE/view?usp=sharing
backlog: https://drive.google.com/file/d/0B2Zd5TrGbCKgN2htSGhlUGVVY3M/view?usp=sharing
add users: https://drive.google.com/file/d/0B2Zd5TrGbCKgN01nQ3R3aXZqem8/view?usp=sharing
add users step 2: https://drive.google.com/file/d/0B2Zd5TrGbCKgWEcyU3FUUzN6WWs/view?usp=sharing (im not sure about that, but lets try)
