### ISSUE TITLE
Document API error response structure

### ISSUE THREAD

**Issue by herkyl** [Teamweek/teamweek#630]

**Comment by marektihkan** [comment]
What about: http://docs.teamweek.apiary.io/#introduction/overview/client-errors

**Comment by herkyl** [comment]
Do we no longer use the github API docs?

**Comment by herkyl** [comment]
Ok it was there, just very hard to find

**Comment by marektihkan** [comment]
Updated wiki with http://docs.teamweek.apiary.io link

**Comment by herkyl** [comment]
Then you also need to update http://support.teamweek.com/api/ since this is n1 on google
