### ISSUE TITLE
In Chrome

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#632]
* backlog
* no need for footer tools (navigation etc)
* weird black lines 
* weird black bottom line 
* i think we should not show those admin stars here

![chrome1 copy](https://cloud.githubusercontent.com/assets/5929570/5924458/95f22476-a664-11e4-874d-afb23351e919.jpg)

![chrome](https://cloud.githubusercontent.com/assets/5929570/5924429/4d68ffc2-a664-11e4-8c74-f3d21ec82921.jpg)

**Comment by miscer** [comment]
Printing was broken in some versions of Chrome, but in 40.0.2214.91 it seems to be working properly.
