### ISSUE TITLE
i should not be able to mark users as admins when they have no emails. 

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#642]
![screen-shot-2015-01-27-at-20 53 16](https://cloud.githubusercontent.com/assets/5929570/5939105/945bdb66-a709-11e4-8b68-16d5986172c9.png)

Talk to Michal about frontend.

**Comment by arcz** [comment]
@miscer I'll add restriction to backend, can you remove button from frontend?

**Comment by arcz** [comment]
Fixed both on frontend and backend
