### ISSUE TITLE
Sign in 

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#649]
Sign in actually should look like that, I don't remember why it got changed. 
![sign_in](https://cloud.githubusercontent.com/assets/5929570/5972419/bec358d0-a861-11e4-8b12-2f49d3d46c02.jpg)

nb! we don't have toggl sign in
code: http://demo.fraktal.ee/teamweek/site/01_front.html

**Comment by marektihkan** [comment]
I got changes, because on teamweek.com page we don't really know if user is signed in or not. And forcing everybody to sign in every time is not nice. Another reason was keeping things same in iPad and web.
