### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#667]
* icons and cancel
* cannot see start/ end time
* estimates (0 is too close)

![img_2783](https://cloud.githubusercontent.com/assets/5929570/6145802/73c13564-b1ee-11e4-8c59-cd7799b07b3e.PNG)
 
* navigation popup is no in the middle (doesn't fit). maybe you can use it like menu. 
![img_2782](https://cloud.githubusercontent.com/assets/5929570/6145809/8c7b5904-b1ee-11e4-95c6-5fc3a8b68a69.PNG)

* this happens when i start to add new tasks (popup):
![img_2781](https://cloud.githubusercontent.com/assets/5929570/6145823/a64cb01c-b1ee-11e4-845e-ff163ce451ed.PNG)

* footer:
![img_2780](https://cloud.githubusercontent.com/assets/5929570/6145833/b4aa60e6-b1ee-11e4-8490-7c140de42745.PNG)

* i don't like the grey boarder around colors. i think we should chance that in web version as well - palette is from edge to edge or with a really thin boarder (e.g. like selected color):
![img_2778](https://cloud.githubusercontent.com/assets/5929570/6145906/7a05bb42-b1ef-11e4-80ba-d38819fc4ff9.PNG)

![colors](https://cloud.githubusercontent.com/assets/5929570/6145976/4dc5b482-b1f0-11e4-877b-817bc02f6c9e.png)

**Comment by herkyl** [comment]
Need to upgrade to a bigger screen @maritmartin :watermelon:

**Comment by maritmartin** [comment]
say it to your grandma

**Comment by marektihkan** [comment]
+1 to upgrade your grandma

**Comment by herkyl** [comment]
This escalated quickly..
