### ISSUE TITLE
Sharing "Shared view" to Social Media

### ISSUE THREAD

**Issue by starfild** [Teamweek/teamweek#680]
When in shared view there needs to be an option to share it to social media (FB and Twitter). 
- In FB it should show a preview as it is with other URL's. Tekst võiks olla "This a shared view from the Teamweek calendar"
- In Twitter is it possible to make it into short-URL? Together with the link tweet should say "Shared calendar view by @teamweek". When clicking on twitter bird, it should open a twitter pop-up window only for tweeting (ie here when you click on the bird: http://www.slate.com/articles/technology/future_tense/2015/02/ssl_warnings_users_ignore_them_can_we_fix_that.html )
![shared_view_social_media](https://cloud.githubusercontent.com/assets/9819262/6224141/bec36c7c-b67f-11e4-9078-9e496ceac2b7.png)

**Comment by herkyl** [comment]
Twitter done, leaving facebook for michal
