### ISSUE TITLE
Sign in

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#691]
sign in:
![iaxd0bbrtlqpnoarsluxwsottvzlbxwaqhx83wvmjqi](https://cloud.githubusercontent.com/assets/5929570/6248674/9998a7bc-b78a-11e4-8052-575e2ab3505a.png)
*(ignore 30 px)*
![rvszcp3tptp9vu8qkr9rxveqp7xi913e5j67r4bqxpi](https://cloud.githubusercontent.com/assets/5929570/6248677/9d63942e-b78a-11e4-95af-8ad4598d0956.png)

forgot password:
![qmyh6kparz3jrbt7ohatx9r7szaeln-gp22vg6neouw](https://cloud.githubusercontent.com/assets/5929570/6248810/92910b3e-b78b-11e4-8165-915cee086072.png)
![zkvf4uawiomiozj5r6d4oidfjoqoqw07d8atxr8l2qo](https://cloud.githubusercontent.com/assets/5929570/6248814/972b7b52-b78b-11e4-9771-85cc1f3385aa.png)

**Comment by miscer** [comment]
I think there should be a link for sign up somewhere as well.
