### ISSUE TITLE
Task rearranging: placeholders (shadow)

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#702]
Place, where i drop it should be parked with the shadow. like when you drag tasks to some other location. 

![krhgsjecq_mjshraquoutqdmynoajily6goctvijin8](https://cloud.githubusercontent.com/assets/5929570/6366959/b06603d6-bcd5-11e4-8497-9e6e59815c31.png)

![rk2znwpzga87mjcl676qhed31ch7uqbko1tgfilfvg8](https://cloud.githubusercontent.com/assets/5929570/6367006/236c806c-bcd6-11e4-82b9-4f9f54b0b422.png)

**Comment by herkyl** [comment]
What happens if you drop something on something else?

**Comment by maritmartin** [comment]
then we should move those tasks to make space between them.
