### ISSUE TITLE
Safari share timeline not auto selecting url

### ISSUE THREAD

**Issue by arcz** [Teamweek/teamweek#714]
Sharing timeline on Safari, when clicking on url it is not being auto selected.

It auto selects when you click on url and then move mouse to some button with icon: cursor, but it is bug anyway.

![zrzut ekranu 2015-02-26 o 21 54 06](https://cloud.githubusercontent.com/assets/4679721/6401698/7fde2cb0-be02-11e4-905d-518b9f2f688d.png)

**Comment by miscer** [comment]
It seems to be a bug in Safari, I can't think of any other explanation for this.
