### ISSUE TITLE
Can't select link with clicking on that (safari) 

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#733]
![screen shot 2015-03-05 at 12 49 37](https://cloud.githubusercontent.com/assets/5929570/6503475/1b128aa4-c336-11e4-90de-01ef414f2716.png)

To copy those links, i have to select it like that: 
![screen shot 2015-03-05 at 12 51 09](https://cloud.githubusercontent.com/assets/5929570/6503502/6764b3d2-c336-11e4-9c2d-fa876bb0760f.png)

**Comment by arcz** [comment]
@maritmartin https://github.com/Teamweek/teamweek/issues/714

**Comment by miscer** [comment]
:point_up:
