### ISSUE TITLE
Adding users in Everyone view when you have inactive users 

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#742]
![1](https://cloud.githubusercontent.com/assets/5929570/6508112/59036e4a-c35f-11e4-9c8d-353994079734.png)

![2](https://cloud.githubusercontent.com/assets/5929570/6508114/5d1fc686-c35f-11e4-89a1-9a424f3cabf2.png)

![3](https://cloud.githubusercontent.com/assets/5929570/6508119/60e98298-c35f-11e4-9694-aaf8f2595038.png)

**Comment by miscer** [comment]
I don't quite understand what you're trying to say :smile:

**Comment by maritmartin** [comment]
It's just illustrative, that you'd know how this should look like when you have inactive users as well.
