### ISSUE TITLE
Arrows in Backlog are misaligned. 

### ISSUE THREAD

**Issue by tiinakaarik** [Teamweek/teamweek#747]
Occurs only in Chrome. Tried refresh, clear cache - didn't work. See screenshot:

![screen shot 2015-03-08 at 22 30 12](https://cloud.githubusercontent.com/assets/7932032/6549535/0506bd8e-c5e3-11e4-9ee8-9de4423b0fb3.png)

**Comment by herkyl** [comment]
Hmm where is this happening to you. App.tw is fine for me on Chrome.
