### ISSUE TITLE
Basecamp integration fails.

### ISSUE THREAD

**Issue by tiinakaarik** [Teamweek/teamweek#757]
app.teamweek.com. When trying to enable the Basecamp integration, an error message "Oops, there was an error and the integration was unsuccessful." is displayed. This is what I see in the console:

![screen shot 2015-03-09 at 12 57 44](https://cloud.githubusercontent.com/assets/7932032/6563470/5af8ff7c-c66f-11e4-9bc2-a6d9147f5bfe.png)

**Comment by janika** [comment]
The new balancer was missing some configuration.
