### ISSUE TITLE
Add keyboard shortcuts to help page

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#758]
* remove one FAQ (last one)
* change some spacing
* show only 2 product news at the same time

Hold Cmd (Ctrl for PC) and drag a task to duplicate it
Perss Cmd (Ctrl for PC) + z to undo your move
Press Cmd (Ctrl for PC) + t to go to Today 

![key-shortcuts](https://cloud.githubusercontent.com/assets/5929570/6574134/23bdaa4c-c72a-11e4-80cc-2532b9b196b4.png)

![shortc](https://cloud.githubusercontent.com/assets/5929570/6574146/62c1221e-c72a-11e4-85b8-fb3e4f885151.png)

**Comment by herkyl** [comment]
There is one more shortcut: b opens/closes the backlog

**Comment by maritmartin** [comment]
@miscer - please try to add a third article under the product news. 

![help](https://cloud.githubusercontent.com/assets/5929570/6592462/9099e114-c7d7-11e4-95bd-8acc480b5ab2.png)
