### ISSUE TITLE
Local vs global milestones 

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#807]
Global (shown in every group): empty 
Local (group based): full 

![69717180](https://cloud.githubusercontent.com/assets/5929570/7293936/cd7e21d4-e9b1-11e4-87a1-e1a61e6e98c7.png)

And add another line here: 
"Make this milestone global" (on/off)  (shown only when you're in a group) 
"Turn this milestone into holiday" (on/off)

![hmac7caenjkhlykfqsm_rh7abtusqiqqajjadaid-i4](https://cloud.githubusercontent.com/assets/5929570/7294579/3f51f772-e9b7-11e4-8822-2be7f832b791.png)

**Comment by marektihkan** [comment]
Is there design changes for global/local holidays?

**Comment by maritmartin** [comment]
holidays are global at the moment (and in the near feature)

**Comment by herkyl** [comment]
Holidays are not global. Holidays works exactly the same as groups right now, since technically holidays are milestones as well
