### ISSUE TITLE
Integrations

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#829]
Case: https://toggl.desk.com/agent/case/152788

**Comment by arcz** [comment]
@herkyl can you take a look, when importing tasks on staging it blows ```Uncaught ReferenceError: loader is not defined``` maybe this causes problems?

**Comment by miscer** [comment]
I have fixed the error and asked the user to try importing tasks again.

**Comment by marektihkan** [comment]
Issue might be that they have deleted user from Basecamp and it fails to import tasks for that user. I asked them to import users again and see if tasks importing works or not.

**Comment by marektihkan** [comment]
Seemed that fixed the issue for them
