### ISSUE TITLE
Backlog task to timeline drag logic 

### ISSUE THREAD

**Issue by kristjanpillak** [Teamweek/teamweek#842]
By default Teamweek give to all backlog inserted tasks length 5 day when you drag them to timeline. People who works only in week view (like myself) it can be a problem. I almost always have to change task period manually.

Is it possible to create feature that when person works in week view then from backlog to timeline dragged task default length is 1 day and when you are in month or 3 months view then default length is 5 days?

**Comment by herkyl** [comment]
:+1: I think it is a good idea

**Comment by herkyl** [comment]
@kristjanpillak The feature is now live!
