### ISSUE TITLE
Popups

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#852]
![1](https://cloud.githubusercontent.com/assets/5929570/7794856/a43fda8a-02d7-11e5-9eda-447fe60bd5c4.png)

![2](https://cloud.githubusercontent.com/assets/5929570/7794941/b982269a-02d8-11e5-87b3-09242c5d05fd.png)

![1](https://cloud.githubusercontent.com/assets/5929570/7795150/b0b2c680-02da-11e5-9fc1-63577566ff60.png)

![2](https://cloud.githubusercontent.com/assets/5929570/7795151/b4a6c80e-02da-11e5-8548-dfffbd61f5ec.png)

**Comment by maritmartin** [comment]
i'll talk with Kaupo about the idea that popup opens always in the center

**Comment by miscer** [comment]
Popup arrow can't be only on the top/bottom, because it doesn't work for tasks that are in the middle of the screen.
