### ISSUE TITLE
Task are offset by 1 day

### ISSUE THREAD

**Issue by miscer** [Teamweek/teamweek#893]

**Comment by miscer** [comment]
In IE, I have a bug when changing the time view from week to month (and back again) - all tasks are offset my 1 day ie Friday becomes Monday. When I click the TW sign, it rights itself.

**Comment by herkyl** [comment]
Cannot reproduce this on Win7 IE11

**Comment by vickiwong** [comment]
It is happening on my Chrome(PC), clicked TW, refreshed, cleared cookies, closed and reopened, still offset.

**Comment by miscer** [comment]
Hi @vickiwong, thanks for the info! In which timezone are you? There have been some issues with Australian timezones.

**Comment by vickiwong** [comment]
London
On 5 Aug 2015 13:04, "Michal Miškerník" <notifications@github.com> wrote:

> Hi @vickiwong <https://github.com/vickiwong>, thanks for the info! In
> which timezone are you? There have been some issues with Australian
> timezones.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Teamweek/teamweek/issues/893#issuecomment-127973219>.
>

-- 
This email and any attachments may be confidential and/or legally 
privileged. If you have received this e-mail and you are not a named 
addressee, please inform the sender. If you are not a named addressee you 
must not use, disclose, distribute, copy, print or rely on this e-mail. Any 
views or opinions presented are solely those of the author. Any statements 
made, or intentions expressed in this communication may not necessarily 
reflect the view of Space Ape Games. Although Space Ape Games routinely 
screen for viruses, addressees should scan this e-mail and any attachments 
for viruses. Space Ape Games make no representation or warranty as to the 
absence of viruses in this e-mail or any attachments.

Space Ape Games (UK) Limited is registered in England and Wales 7956131. 
Space Ape Games, 25 Soho Square, London, UK, W1D 3QR  www.spaceapegames.com

**Comment by vickiwong** [comment]
![image](https://cloud.githubusercontent.com/assets/3500662/9088836/ffe5b158-3b89-11e5-995e-b0ff086aea27.png)

**Comment by miscer** [comment]
Thanks for the screenshot, we will look into it.

**Comment by miscer** [comment]
Related support cases 178715 and 179117.

**Comment by miscer** [comment]
Fixed.
