### ISSUE TITLE
Created tasks get duplicated sometimes

### ISSUE THREAD

**Issue by miscer** [Teamweek/teamweek#916]
> sometimes created tasks get duplicated, usually the second one has no description and it happens when i use enter as save.

![image](https://cloud.githubusercontent.com/assets/1036313/8448732/099b4404-1fcb-11e5-98cd-7a2f0654dc67.png)

**Comment by herkyl** [comment]
Has anyone noticed this any more?

**Comment by herkyl** [comment]
Closing this for now, since it hasn't been reported since
