### ISSUE TITLE
Task lineup tuning - earlier tasks should be upper automatically

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#923]
Earlier tasks should be upper - e.g. if there are 2 or more overlapping tasks, then those beginning earlier, should be rendered in top positions. If tasks have the same beginning, then those ending earlier should have upper position. See attached screenshot

![screen shot 2015-07-01 at 16 41 38](https://cloud.githubusercontent.com/assets/5136955/8455865/63e41f40-2010-11e5-86c2-dea5c615b82b.png)

**Comment by herkyl** [comment]
But these tasks were arranged that way. If we have free task arrangement then we cannot force them into any order. I remember that Alari originally talked about a different case in the 3months planning event.

**Comment by herkyl** [comment]
We discussed it with Alari and formulated this task description:

New tasks (and stretched tasks?) should hold the same row that they are created on when stretching them. Right now they get a static weight assigned to them but in the next column that weight might go to a different row, hence the jumping tasks when stretching.
