### ISSUE TITLE
Tooltips should always appear next to the mouse cursor, not in the centre of the elements. 

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#931]

**Comment by herkyl** [comment]
This cannot be done using the CSS tooltips that give us a major performance boost

**Comment by maritmartin** [comment]
But for example sometimes i cannot see task's tooltip when it's too long and out of my screen. And Kaupo also said that the current version is a bit weird.

**Comment by herkyl** [comment]
Then we need to use a JavaScript based tooltips system, like we had before
