### ISSUE TITLE
Allow admins to upload pictures for other users 

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#936]
this view should appear when you click on the color square. 

![screen shot 2015-07-07 at 14 26 14](https://cloud.githubusercontent.com/assets/5929570/8545147/35b6f9a0-24b4-11e5-9300-3600cb3893f6.png)

there should also be an option to remove that picture, like in the settings page.

**Comment by miscer** [comment]
Uploading pictures for other users needs to be implemented in the backend.

**Comment by ronilaukkarinen** [comment]
Yes, an option to choose picture for the dummy users would be awesome. +1 for me.

**Comment by ronilaukkarinen** [comment]
So this is now implemented?

**Comment by miscer** [comment]
@ronilaukkarinen Yes :) You can upload a picture by clicking on the colour button in the user popup.
