### ISSUE TITLE
New loader

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#943]
Green line like here: http://onextrapixel.com/examples/youtube-like-ajax-loading-bar/
And maybe light fade while it's loading?

**Comment by maritmartin** [comment]
waiting for feedback on what?

**Comment by herkyl** [comment]
check out the loader at https://michal.teamweek.com/#timeline

**Comment by maritmartin** [comment]
i think it's too bold at the moment. but otherwise looks awesome and can go live.

**Comment by maritmartin** [comment]
Make it a bit narrower (height) and put live
