### ISSUE TITLE
Put all the integrations under one page (Export & Import)

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#955]
![88437274](https://cloud.githubusercontent.com/assets/5929570/8669457/82ab120a-2a1d-11e5-9df2-e0de84792306.png)
![88437275](https://cloud.githubusercontent.com/assets/5929570/8669467/9a0519e6-2a1d-11e5-860d-9e68a9208315.png)
![89239083](https://cloud.githubusercontent.com/assets/5929570/8669472/a3e746fa-2a1d-11e5-9e3d-e937c835bf8b.png)

**Comment by maritmartin** [comment]
![88437274 copy](https://cloud.githubusercontent.com/assets/5929570/8930213/af37936c-3534-11e5-927f-d425e4303230.png)

**Comment by maritmartin** [comment]
Guys, this is not how we work! I understand if you don't notice a couple of pixels, but here you have just ignored the design: 

![88437275](https://cloud.githubusercontent.com/assets/5929570/8930251/1f2fa1be-3535-11e5-8ef1-edcf590516cb.png)

![wqjsi3due-ettmgntcg80mknd0zeqxyngpdlbt9sb5s](https://cloud.githubusercontent.com/assets/5929570/8930252/2326511e-3535-11e5-986d-9fbb9044789d.png)

**Comment by maritmartin** [comment]
1. see the difference here: 
![8iip-viyt8lboqmznggyokqyeu7ku14cpvc9ordjieg](https://cloud.githubusercontent.com/assets/5929570/9109712/59955530-3c40-11e5-8b69-1ec539a396d7.png)
![af37936c-3534-11e5-927f-d425e4303230](https://cloud.githubusercontent.com/assets/5929570/9109714/5bd6cdec-3c40-11e5-98da-0d66f1d294cb.png)

**Comment by maritmartin** [comment]
2. And i feel like the integrations popup is a bit wider than the settings popup.

**Comment by miscer** [comment]
We don't have that nice and shiny Basecamp icon :disappointed:

**Comment by miscer** [comment]
> others can be added later from the bottom left icon

I don't think it makes a lot of sense without the icon in the text
