### ISSUE TITLE
Adding tasks

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#957]
Shown:
Description 
Project
Daily Estimate
Dates (not time, like it's in the mockup)

Hidden:
Time (start/ end time) - displayed like dates
Notes 

![88014976](https://cloud.githubusercontent.com/assets/5929570/8669541/308bef8e-2a1e-11e5-9a38-6f2a3171aeb4.png)

**Comment by herkyl** [comment]
What changed?

**Comment by maritmartin** [comment]
1. put notes and start/ end time under one icon
![more2](https://cloud.githubusercontent.com/assets/5929570/9109397/07a3cb14-3c3e-11e5-8d3d-831078a61a26.png)
icon: https://drive.google.com/a/toggl.com/file/d/0B2Zd5TrGbCKgak5fMGJLMk9WOUE/view?usp=sharing

2. the order: 
project
daily estimate
dates
notes 
time
