### ISSUE TITLE
Allow uploading avatar for dummy users

### ISSUE THREAD

**Issue by ronilaukkarinen** [Teamweek/teamweek#973]
Hello! We would like to make dummy users distinct from the real users by adding an avatar for them. This feature would be great!

**Comment by herkyl** [comment]
Hey @ronilaukkarinen, thanks for the issue. This is actually a planned feature!

**Comment by herkyl** [comment]
I found the relevant issue #936. Closing this issue for now, please follow the other one @ronilaukkarinen

**Comment by ronilaukkarinen** [comment]
Ok, thank you @herkyl, I will.
