### ISSUE TITLE
latest android app - cannot save time

### ISSUE THREAD

**Issue by triinjassov** [Teamweek/teamweek#989]
steps to reproduce:

- create a new task
- set time (for example 13.00)
- not possible to save ( only options "cancel" or "clear")

**Comment by miscer** [comment]
What's the android version?

**Comment by triinjassov** [comment]
Android versioon: 5.0.2

Phone: SM-A500FU

**Comment by miscer** [comment]
This is a bug in Cordova, which is an external tool. The issue should get fixed when #996 is done.
